### ISSUE TITLE
Issues regarding the LMDB dataset creating.

### ISSUE THREAD

**Issue by nile649** [rosinality/alias-free-gan-pytorch#28]
Traceback (most recent call last):
  File "train.py", line 404, in <module>
    conf = load_arg_config(GANConfig)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/tensorfn/util/config.py", line 269, in load_arg_config
    conf = load_config(config_model, args.conf, args.opts, show)
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/tensorfn/util/config.py", line 257, in load_config
    conf = config_model(**read_config(config, overrides=overrides))
  File "/home/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/tensorfn/util/config.py", line 25, in read_config
    json_str = _jsonnet.evaluate_file(config_file)
AttributeError: 'NoneType' object has no attribute 'evaluate_file'

data format.
```
-Data
--Images
---1.jpg
|
|
|
---N.jpg
```

**Comment by rosinality** [comment]
You will need to install jsonnet packages by `pip install jsonnet`.
